[project]
name = "openpi"
version = "0.1.0"
description = "Physical Intelligence open source repo"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
dependencies = [
    "flax==0.9.0",
    "jax[cuda12]==0.4.34",
    "jaxtyping==0.2.34",
    "orbax-checkpoint==0.7.0",
]

[project.urls]
Repository = "https://github.com/Physical-Intelligence/openpi"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
