[project]
name = "openpi-client"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "dm-tree>=0.1.8",
    "msgpack>=1.1.0",
    "numpy>=1.26.4",
    "pillow>=9.0.0",
    "tree>=0.2.4",
    "websockets>=12.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
]
