[project]
name = "openpi-client"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.26.4",
    "websockets>=12.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"