# Run with:
# docker compose -f scripts/compose.yml up --build
services:
  openpi_server:
    image: openpi_server
    build:
      context: ..
      dockerfile: scripts/serve_policy.Dockerfile
    init: true
    tty: true
    network_mode: host
    volumes:
      - $PWD:/app

    # Comment out this block if not running on a machine with GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
