# Run with:
# docker compose -f examples/aloha_real/compose.yml up --build
services:
  runtime:
    image: aloha_real
    depends_on:
      - aloha_ros_nodes
      - ros_master
      - pi0_server
    build:
      context: ../..
      dockerfile: examples/aloha_real/Dockerfile
    init: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - $PWD:/root/app
      - ../../data:/data

  aloha_ros_nodes:
    image: aloha_real
    depends_on:
      - ros_master
    build:
      context: ../..
      dockerfile: examples/aloha_real/Dockerfile
    init: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
    command:
      - /bin/bash
      - -c
      - |
        sed -i 's/CAM_HIGH_SERIAL/128422271950/g' /root/interbotix_ws/src/aloha/launch/ros_nodes.launch
        sed -i 's/CAM_LOW_SERIAL/218622272463/g' /root/interbotix_ws/src/aloha/launch/ros_nodes.launch
        sed -i 's/CAM_LEFT_WRIST_SERIAL/218622277019/g' /root/interbotix_ws/src/aloha/launch/ros_nodes.launch
        sed -i 's/CAM_RIGHT_WRIST_SERIAL/218622277645/g' /root/interbotix_ws/src/aloha/launch/ros_nodes.launch
        roslaunch --wait aloha ros_nodes.launch

  ros_master:
    image: ros:noetic-robot
    network_mode: host
    privileged: true
    command:
      - roscore

  pi0_server:
    image: pi0_server
    build:
      context: ../..
      dockerfile: src/openpi/serving/Dockerfile
    init: true
    tty: true
    network_mode: host
    volumes:
      - $PWD:/app

    # Comment out this block if not running on a machine with GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
